proyecto/django/backend/backend/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('',include('videos.urls')),
    #path('videos/',include('videos.urls')),

    path('cuentas/',include('cuentas.urls')),
]
urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)#indico la ruta de los videos e imagenes

proyecto/django/backend/cuentas/urls.py
from django.urls import path
from . import views
from rest_framework import routers
from .viewsets import UserViewSet
from rest_framework.authtoken.views import ObtainAuthToken
#from django.views.decorators.csrf import csrf_exempt

app_name='usuarios'

#router = routers.SimpleRouter()#django rest framework hacer rutas
#router.register('users', UserViewSet)#django rest framework registrarlas
#urlpatterns=router.urls#django rest framework poder buscarlas

urlpatterns = [
 #   path(r'autenticar/',ObtainAuthToken.as_view()),
   
    path('signup/',views.registrarse,name='registrarse'),#vista que se cargara para iniciar el registro de un nuevo usuario
    path('login/',views.login_u,name='login'),#vista loguear usuario
    path('logout/',views.logout_u,name='logout'),#desloguear usuario
    path('perfil/',views.mirar_perfil,name="perfil"),#vista perfil
    path('modificar_p/',views.modificar_p_u,name='modificar_p_u'),#cambiar contraseña
    path('plantilla_p/',views.plantilla_contra_n,name='plantilla_p'),#plantilla cambiar contraseña
    path('plantilla_mod_u/',views.plantilla_mod_u,name='plantilla_mod_u'),#plnatilla cambiar datos de usuario
    path('cambios_perfil/',views.cambios_perfil,name="hacer_cambios_perfil"),

]

proyecto/django/backend/videos/urls.py
from django.urls import path
from . import views
from rest_framework import routers
from .viewsets import VideosViewSet,ComentariosViewSet,SeriesViewSet

app_name='videos'
#router = routers.SimpleRouter()
#router.register('todos',VideosViewSet)
#router.register('series',SeriesViewSet)
#router.register('comentarios',ComentariosViewSet)


#urlpatterns=router.urls
urlpatterns = [
    path('',views.home,name='home'),#vista que cargara al entrar en /videos
    path('video/<int:id_video>',views.video_concreto,name='video'),#vista que cargara al entrar en /videos/prueba
    path('nuevo_comentario/',views.nuevo_comentario,name='nuevo_comentario'),
    #path('comentarios/',views.t_comentarios,name='comentarios'),
    path('modificar_comentario/<int:id_comentario>',views.modificar_comentario,name='modificar_comentario'),
    path('buscar/',views.buscar_serie,name='buscar_serie'),
    path('videos_serie/<int:id_serie>',views.mostrar_videos_serie,name="videos_serie"),
]

proyecto/django/backend/videos/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class videos(models.Model):#nombre de la tabla que se creara en la base de datos al hacer un migrate
    nombre= models.CharField(max_length=100,unique=True,help_text='Titulo del video')#campo de texto con el nombre de cada video
    fecha= models.DateTimeField(auto_now_add=True)#campo automatico con la fecha en la cual se ha creado la nueva row en la tabla
    imagen= models.ImageField(default='default.png',blank=True)#campo tipo imagen para poder guardar la ruta de las imagenes
    video= models.FileField(default="default.mp4")#campo tipo file para guardar archivos de video
    serie= models.ForeignKey('series',on_delete=models.CASCADE,default='1')#campo para ligar esta tabla a la tabla series
    
    def __str__(self):
        return self.nombre
        
class series(models.Model):
    nombre= models.CharField(max_length=100,unique=True,help_text='Titulo de la serie')#titulo de la serie que sera unico
    fecha= models.DateTimeField(auto_now_add=True)#fecha de creacion
    ImagenPortada= models.ImageField(default='default.png',blank=True)#imagen
    def __str__(self):
        return self.nombre


class comentarios(models.Model):
    autor= models.ForeignKey(User,default=None,on_delete=models.CASCADE)
    fecha= models.DateTimeField(auto_now_add=True)
    texto= models.CharField(max_length=300)
    video= models.ForeignKey('videos',on_delete=models.CASCADE,default='1')

proyecto/django/backend/videos/forms.py
from django import forms
from . import models

class CrearComentario(forms.ModelForm):
    class Meta:
        model=models.comentarios
        fields=['texto','video']
 

proyecto/django/backend/videos/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import videos,comentarios,series
from django.http import JsonResponse#enviar en formato json

from django.http import HttpResponse
from django.core import serializers#cambiar a formato json
from django.contrib.auth.decorators import login_required#requiere inicio de sesion
from . import forms#importar formulario para los nuevos comentarios
from django.views.decorators.clickjacking import xframe_options_sameorigin#cargar videos

#vista principal
def home(request):
    todos_los_videos=videos.objects.all()#obtengo todos los datos de la tabla de videos
    context = {'todos_los_videos':todos_los_videos}#guardo los datos cogidos en un diccionario el cual le asigno como clave/variable 'todos_los_videos' para su futura utilizacion en la template a la que se lo pasare
    #print(todos_los_videos)
    return render(request,'index.html',context)#envio los datos recibidos a una template renderizando lo obtenido en la tabla
#reproducir video 
@xframe_options_sameorigin
def video_concreto(request,id_video):
    try:#mirar si tiene comentarios        
        t_comentarios=comentarios.objects.filter(video_id=id_video)
    except:#pasarlo vacio si no tiene ningun comentario
        t_comentarios=""
    video=get_object_or_404(videos,id=id_video)#obtengo el video solicitado  
    return render(request,'videos.html',{'video':video,'comentarios':t_comentarios})
#añadir comentario
@login_required(login_url="/cuentas/login/")
def nuevo_comentario(request):
    if request.method == 'POST':
        formulario_comentario=forms.CrearComentario(request.POST,request.FILES)
        if formulario_comentario.is_valid():
            instancia=formulario_comentario.save(commit=False)
            instancia.autor=request.user
            instancia.save()
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('/')         
    return redirect('/')
#modificar comentario
@login_required()
def modificar_comentario(request,id_comentario):
    if request.method == 'POST':
            comentario_m=comentarios.objects.filter(pk=id_comentario).update(texto=request.POST.get('texto'))        
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                redirect('/')
    return redirect('/')
#borrar comentario
def borrar_comentario(request,id_comentario):
    return
#boton de busqueda + vistas
def buscar_serie(request):
        try:  
            series_b=series.objects.filter(nombre__icontains=request.POST.get('serie'))
            cuantos=series.objects.filter(nombre__icontains=request.POST.get('serie')).count()
        except:
            series_b=''
            cuantos=0
        if cuantos==0:
            return redirect('/')
        else:
            return render(request,'buscar.html',{'series':series_b})
def mostrar_videos_serie(request,id_serie): 
        try:
            videos_s=videos.objects.filter(serie_id=id_serie)
            cuantos=videos.objects.filter(serie_id=id_serie).count()
        except:
            videos_s=''
            cuantos=0
        if cuantos==0:
           return render(request,'index.html',{'todos_los_videos':videos_s,'noEncontrados':'No se han encontrado videos de esta serie'})
        else:      
            return render(request,'index.html',{'todos_los_videos':videos_s})

proyecto/django/backend/videos/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>VideossoediV</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

</head>
<body>
<!--Navbar-->
    <nav class="navbar navbar-expand-lg  navbar-dark bg-dark static-top">
        <div class="container">
          <a class="navbar-brand" href="/">
              <img src="/imagenes/logo.png" alt="Logo" class="img-responsive">
              </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
                      <ul class="navbar-nav mr-auto  d-flex justify-content-end">
                        
                          <form class="form-inline" method="POST" action="{% url 'videos:buscar_serie'%}">
                            {%csrf_token%}
                            <input class="form-control mr-sm-2"name="serie" type="search" placeholder="Search" aria-label="Search">
                            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
                          </form>
                        
                      </ul>
                      <ul class="navbar-nav navbar-right d-flex justify-content-end">
                        {%if user.is_authenticated%}
                        <li>
                          <a class=" btn btn-secondary" role="button" href="{% url 'usuarios:perfil' %}">Perfil</a>
                        </li>
                          <li>
                            <form action="{% url 'usuarios:logout' %}" method="POST">
                              {% csrf_token %}
                              <input class=" btn btn-danger"type="submit" value="desconectarse">
                            </form>
                          </li>
                          
                          {% else %}
                          <li class="nav-item">
                            <a class=" btn btn-primary" role="button" href="{% url 'usuarios:login' %}">Conectarse</a>
                           </li>
                           <li class="nav-item">
                             <a href="{% url 'usuarios:registrarse' %}" class="btn btn-primary " role="button">Registrarse</a> 
                           </li>
                          {% endif %}
                      </ul>
          </div>
          </div>
    </nav>
<!--/Navbar-->
      


{% block content %}
   
{% endblock %}

<!--Scripts-->
<script>
  document.body.style.backgroundImage="url(/imagenes/fondo.png)"
  
</script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<!--/Scripts-->


</body>
</html>

proyecto/django/backend/videos/templates/buscar.html
{%extends 'base.html'%}
{%block content%}
    {%if series%}<!--si hay series pintar las imagenes-->
    <div class="container">
        <div class="row">
        {%for serie in series%}
            {%if forloop.counter|divisibleby:5 %}
                </div>
                <div class="row">
            {% endif %}               
                <div class="card" style="width: 18rem;">
                    <a href="{% url 'videos:videos_serie' serie.id%}">
                    <img class="card-img-top" src="{{serie.ImagenPortada.url}}" alt="Card image cap">
                    </a>    
                    <div class="card-body">
                      <h5 class="card-title">{{serie.nombre}}</h5>
                      
                    </div>
                  </div>              
            {% if forloop.last %} 
                </div> 
            {%endif%}                      
        {%endfor%}
    </div>
    {%endif%}

{%endblock%}

proyecto/django/backend/videos/templates/index.html
{% extends 'base.html'%}
{% block content %}
{%if noEncontrados%}
<div class="container">
    <div class="row  text-danger" >
        <h1>{{noEncontrados}}</h1>
    </div>
</div>  
{%endif%}
<div class="container">
    <div class="row  justify-content-center">
        {% if todos_los_videos %}
            {% for video in todos_los_videos %}
                {%if forloop.counter|divisibleby:4 %}
                </div>
                <div class="row  justify-content-center">

                {% endif %}
                <div class="card" style="width: 18rem;">
                    <a href="{% url 'videos:video' video.id%}">
                    <img class="card-img-top" src="{{video.imagen.url}}" alt="Card image cap">
                    </a>    
                    <div class="card-body">
                      <h5 class="card-title">{{video.nombre}}</h5>
                      
                    </div>
                  </div>               
                
                {% if forloop.last %} 
                </div> 
                {%endif%}                           
            {% endfor %}
        {% else %}
        {% endif %}
    

</div>
    
{% endblock%}

proyecto/django/backend/videos/templates/nuevo_comentario.html
{% extends 'base.html' %}
{% block content%}
<div class="nuevo-comentario">
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form}}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{request.GET.next}}">
        {% endif %}
        <input type="submit" value="Añadir comentario">
    </form>
</div>
{% endblock%}

proyecto/django/backend/videos/templates/videos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>VideossoediV</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

</head>
<body>
<!--Navbar-->
    <nav class="navbar navbar-expand-lg  navbar-dark bg-dark static-top">
        <div class="container">
          <a class="navbar-brand" href="/">
              <img src="/imagenes/logo.png" alt="Logo" class="img-responsive">
              </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav mr-auto  d-flex justify-content-end">
                        <form class="form-inline" method="POST" action="{% url 'videos:buscar_serie'%}">
                            {%csrf_token%}
                            <input class="form-control mr-sm-2" type="search" placeholder="Search" name="serie" aria-label="Search">
                            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
                        </form>
                    </ul>
                      <ul class="navbar-nav navbar-right d-flex justify-content-end">
                          {% if user.is_authenticated  %}
                          <li>
                            <a class=" btn btn-secondary" role="button" href="{% url 'usuarios:perfil' %}">Perfil</a>
                          </li>
                          <li>
                            <form action="{% url 'usuarios:logout' %}" method="POST">
                            {% csrf_token %}
                            <input class=" btn btn-danger"type="submit" value="desconectarse">
                          </form>
                            </li>
                            
                          {% else %}
                          <li class="nav-item">
                            <a class=" btn btn-primary" role="button" href="{% url 'usuarios:login' %}">Conectarse</a>
                           </li>
                           <li class="nav-item">
                             <a href="{% url 'usuarios:registrarse' %}" class="btn btn-primary " role="button">Registrarse</a> 
                           </li>
                          {%endif%}
                      </ul>
          </div>
          </div>
    </nav>
<!--/Navbar-->
      


{% block content %}
<!--video-->
<div class="container">
    <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="{{video.video.url}}" allowfullscreen></iframe>
    </div>
</div>
    
<!--comentarios-->
    <div class="container text-center">
        <h1>Comentarios</h1>    
        {% if comentarios %}
            {% for comentario in comentarios%}
            {%ifequal comentario.autor_id user.id%}
            <div class="row  justify-content-center" id="comentario{{comentario.id}}">
                <p class="col-12" >{{comentario.texto}}</p>
                <p class="col-12">{{comentario.fecha}}</p>
                <button id="modificar_{{comentario.id}}" onclick="mostrar_form({{comentario.id}})" class="btn btn-secondary">Modificar</button>
            </div>
            <div class="row justify-content-center" id="form{{comentario.id}}" style='display:none'>
                <div class="form-group">
                    <form action="{% url 'videos:modificar_comentario' comentario.id%}" class="col-12"method="POST">
                        {% csrf_token%}
                        <textarea type="text"name="texto"class="form-control form-control-lg"id="texto" placeholder="{{comentario.texto}}"value="{{comentario.texto}}"></textarea>               
                        <input type="hidden" name="next" value="{%url 'videos:video' video.id%}">
                        <input type="submit" class="btn btn-primary" value="Guardar cambios">
                    </form>
                    <button class="btn btn-danger" onclick="ocultar_form({{comentario.id}})">Cancelar</button>
                </div>
            </div>           
            {% else %}
                <div class="row justify-content-center">
                    <p class="col-12">{{comentario.texto}}</p><br>
                    <p class="col-12">{{comentario.fecha}}</p>
                </div>
            {%endifequal%}
            {% endfor%}    
        {% endif %}       
    </div>
<!--añadir comentario-->  
    {% if user.is_authenticated %}

        <div class="container justify-content-center" id="añadir_comentario">
            <div class="row">
                <div class="form-group">
                    <form action="{%url 'videos:nuevo_comentario'%}" method="POST">
                        {% csrf_token %}
                        <input type="text"name="texto" id="texto" placeholder="comentario">
                        <input type="hidden" class="form-control form-control-lg" name="video"id="id_video" value="{{video.id}}">
                        <input type="hidden" name="next" value="{%url 'videos:video' video.id%}">
                        <input type="submit" value="Enviar" class="btn btn-primary">
                    </form>
                </div>
                
            </div>
            <button class="btn btn-danger"id="nuevo_comentario">Añadir</button>
        </div>         
    {% endif%}
    {% endblock %}
<!--Scripts-->
<script>
    function mostrar_form(comentario_id){
        var formulario=document.getElementById('form'+comentario_id+'');
        var comentario=document.getElementById('comentario'+comentario_id+'');
        formulario.style.display='flex';
        comentario.style.display='none'
     }
    function ocultar_form(comentario_id){
        var formulario=document.getElementById('form'+comentario_id+'');
        var comentario=document.getElementById('comentario'+comentario_id+'');
        formulario.style.display='none'
        comentario.style.display='flex'
    }
    function añadir_comentario(){
        var div=document.getElementById('añadir_comentario')
        div.style.display='flex'
        var boton=document.getElementById('nuevo_comentario')
        boton.
    }
    function cancelar_comentario(){
        var div=document.getElementById('añadir_comentario')
        div.style.display='none'
        
    }
</script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<!--/Scripts-->


</body>
</html>