proyecto/django/backend/backend/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('',include('videos.urls')),
    #path('videos/',include('videos.urls')),

    path('cuentas/',include('cuentas.urls')),
]
urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)#indico la ruta de los videos e imagenes

proyecto/django/backend/cuentas/urls.py
from django.urls import path
from . import views
from rest_framework import routers
from .viewsets import UserViewSet
from rest_framework.authtoken.views import ObtainAuthToken
#from django.views.decorators.csrf import csrf_exempt

app_name='usuarios'

#router = routers.SimpleRouter()#django rest framework hacer rutas
#router.register('users', UserViewSet)#django rest framework registrarlas
#urlpatterns=router.urls#django rest framework poder buscarlas

urlpatterns = [
 #   path(r'autenticar/',ObtainAuthToken.as_view()),
   
    path('signup/',views.registrarse,name='registrarse'),#vista que se cargara para iniciar el registro de un nuevo usuario
    path('login/',views.login_u,name='login'),#vista loguear usuario
    path('logout/',views.logout_u,name='logout'),#desloguear usuario
    path('perfil/',views.mirar_perfil,name="perfil"),#vista perfil
    path('modificar_p/',views.modificar_p_u,name='modificar_p_u'),#cambiar contraseña
    path('plantilla_p/',views.plantilla_contra_n,name='plantilla_p'),#plantilla cambiar contraseña
    path('plantilla_mod_u/',views.plantilla_mod_u,name='plantilla_mod_u'),#plnatilla cambiar datos de usuario
    path('cambios_perfil/',views.cambios_perfil,name="hacer_cambios_perfil"),

]

proyecto/django/backend/videos/urls.py
from django.urls import path
from . import views
from rest_framework import routers
from .viewsets import VideosViewSet,ComentariosViewSet,SeriesViewSet

app_name='videos'
#router = routers.SimpleRouter()
#router.register('todos',VideosViewSet)
#router.register('series',SeriesViewSet)
#router.register('comentarios',ComentariosViewSet)


#urlpatterns=router.urls
urlpatterns = [
    path('',views.home,name='home'),#vista que cargara al entrar en /videos
    path('video/<int:id_video>',views.video_concreto,name='video'),#vista que cargara al entrar en /videos/prueba
    path('nuevo_comentario/',views.nuevo_comentario,name='nuevo_comentario'),
    #path('comentarios/',views.t_comentarios,name='comentarios'),
    path('modificar_comentario/<int:id_comentario>',views.modificar_comentario,name='modificar_comentario'),
    path('buscar/',views.buscar_serie,name='buscar_serie'),
    path('videos_serie/<int:id_serie>',views.mostrar_videos_serie,name="videos_serie"),
]

proyecto/django/backend/cuentas/models.py
from django.db import models

# Create your models here.

proyecto/django/backend/cuentas/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class NUser(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2","first_name","last_name")
class modPass(UserCreationForm):
    class Meta:
        model = User
        fields=("password1","password2","password")

class modifi_user(UserCreationForm):
    class Meta:
        model = User
        fields=("email","first_name","last_name")
   

proyecto/django/backend/cuentas/views.py
from django.shortcuts import render,redirect

from django.contrib.auth.forms import UserCreationForm,AuthenticationForm #necesario para la creacion de usuarios y para conectarse
from django.contrib.auth import login,logout #logear usuarios y deslogear
from .forms import NUser,modPass,modifi_user#forms personalizados
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth.hashers import check_password,make_password,is_password_usable
# Create your views here.
#registrarse
def registrarse(request):
    if request.method == 'POST':#si alguien ha mandado los datos ya rellenados del post ira aqui para crear el nuevo usuario
        formulario= NUser(request.POST)#guardaremos el formulario enviado en una variable
        if formulario.is_valid():
            usuario=formulario.save()#guardar usuario
            login(request,usuario)#iniciar sesion del usuario creado
            return redirect('/')
    else:
        formulario= NUser()
        return render(request,'registrarse.html',{'form': formulario})#redirigir a la pagina de registro de usuarios
#iniciar sesion de usuario
def login_u(request):
    if request.method == 'POST':
        formularioAu=AuthenticationForm(data=request.POST)#rellenar formulario x defecto de autenticacion
        if formularioAu.is_valid():#mirar si es valido
            usuario=formularioAu.get_user()#coger el usuario del formulario
            if usuario is not None:
                login(request, usuario)#iniciar sesion del usuario
                        
            if 'next' in request.POST:#si ha intentado entrar a otra pagina sin loguearse vendra aqui y volvera a la misma despues de loguearse
                return redirect(request.POST.get('next'))#esto lo redirige a la pagina que habia intentado entrar sin loguearse
            else:
                return redirect('/')
    else:
        formularioAu=AuthenticationForm()#formulario vacio con los campos necesarios 
    return render(request,'login.html',{'form':formularioAu})

def logout_u(request):
    if request.method == 'POST':
        logout(request)
    return  redirect('/')
@login_required()
#mirar perfil de usuario
def mirar_perfil(request):
    usuario_m=User.objects.get(pk=request.user.id)
    return render(request,'mirar_perfil.html',{'usuario':usuario_m})
######################################################
#cambiar contraseña pero no funciona, la guarda mal
@login_required()
def modificar_p_u(request):
     if request.method == 'POST':
        formulario= modPass(request.POST)
        if formulario.is_valid():
            usuario_mod=User.objects.get(pk=request.user.id)
            if check_password(request.POST.get('password'),getattr(usuario_mod,'password')):
                if is_password_usable(request.POST.get('password')):
                    n_contraseña=make_password(request.POST.get('password1'))
                    ########## no logro cambiar bien la contraseña~#################
                    if is_password_usable(n_contraseña):
                        
                        usuario_mod.set_password(n_contraseña)
                        usuario_mod.save()
                        return render(request,'mirar_perfil.html',{'usuario':usuario_mod})
                    else:
                        return render(request,'mod_pass.html',{'usuario':usuario_mod,'error':'contraseña invalida'})
                else:
                    return render(request,'mod_pass.html',{'usuario':usuario_mod,'error':'La contraseña nueva no es válida'})
            else:
                return render(request,'mirar_perfil.html',{'usuario':request.user})
            
        formularioP=modPass()
        return render(request,'mod_pass.html',{'formulario':formularioP,'error':'no coincide la contraseña actual'})
@login_required()
def plantilla_contra_n(request):
    return render(request,'mod_pass.html',{'usuario':request.user})
##########################################################################
#modificar perfil
@login_required()
def plantilla_mod_u(request):
    return render(request,'mod_perfil.html',{'usuario':request.user})
@login_required()
def cambios_perfil(request):
        if request.method == 'POST':
            usuario_modificado=User.objects.filter(pk=request.user.id).update(last_name=request.POST.get('last_name'),first_name=request.POST.get('first_name'),email=request.POST.get('email'))
            return render(request,'mirar_perfil.html',{'usuario':request.user})         
        else:
            return render(request,'mod_perfil.html',{'usuario':request.user})

proyecto/django/backend/cuentas/templates/login.html
{% extends 'base.html'%}
{%block content %}
<div class="container text-white mt-4">
    <form action="{% url 'usuarios:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="username">Usuario</label>
            <input type="text" class="form-control" id="username" name="username" placeholder="introducir usuario">
            
          </div>
          <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" id="password" name="password" placeholder="Contraseña">
          </div>
          
        
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{request.GET.next}}">
        {% endif %}
        <input type="submit" class="btn btn-primary" value="Entrar">
    </form>
</div>
{% endblock %}

proyecto/django/backend/cuentas/templates/mirar_perfil.html
{% extends 'base.html' %}
{% block content %}
{%if error%}
{{error}}
{%endif%}
    <div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header text-center"> <h1><i class="fa fa-user"></i>Hola {{usuario.username}}</h1> </div>
                <div class="card-body">                                                                               
                    <div class="row">Nombre: {{usuario.first_name}} </div>
                    <div class="row">Apellido: {{usuario.last_name}}</div>
                    <div class="row">Correo: {{usuario.email}}</div>
                    <div class="row text-center">
                    <a href="{%url 'usuarios:plantilla_mod_u' %}" class="btn btn-primary mb-1">Modificar perfil</a>
                    <a href="{%url 'usuarios:plantilla_p' %}" class="btn btn-secondary mb-1">Modificar contraseña</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{%endblock%}

proyecto/django/backend/cuentas/templates/mod_pass.html
{% extends 'base.html'%}
{% block content %}
 {%if error %}
 <h1>{{error}}</h1>
 {%endif%}
<form action="{%url 'usuarios:modificar_p_u'%}" method="POST">
    {%csrf_token%}
    <input type="password" name="password" id="password"placeholder="contraseña actual"required>
    <input type="password"name="password1" id="password1"placeholder="nueva contraseña"required>
    <input type="password"name="password2" id="password2 laceholder="confirmar nueva contraseña" required>
    <input type="submit" class="button" value="confirmar">
    <a role="button" class="btn btn-danger" href="{%url 'usuarios:perfil'%}">cancelar</a>
</form>
{%endblock%}

proyecto/django/backend/cuentas/templates/mod_perfil.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header text-center"> <h1><i class="fa fa-user"></i>Hola {{usuario.username}}</h1> </div>
                    
                    <form action="{%url 'usuarios:hacer_cambios_perfil' %}"method="post">
                        {%csrf_token%}
                        <input type="text" name="email"id="email" value="{{usuario.email}}" placeholder="{{usuario.email}}">
                        <input type="text" name="first_name" id="first_name"value="{{usuario.first_name}}" placeholder="{{usuario.first_name}}">
                        <input type="text" name="last_name"id="last_name"value="{{usuario.last_name}}" placeholder="{{usuario.last_name}}">
                        
                            <input type="submit" class="btn btn-primary mb-1" value="guardar cambios">
                            <a href="{%url 'usuarios:perfil'%}" class="btn btn-danger mb-1">cancelar</a>                       
                        
                    </form>
            </div>
        </div>
    </div>
</div>

{%endblock%}

proyecto/django/backend/cuentas/templates/registrarse.html
{% extends 'base.html' %}
{% block content %}
<!--REGISTRO DE CUENTAS DE USUARIO-->
<div class="container text-white">
<form action="{% url 'usuarios:registrarse' %}" method="POST">
    {% csrf_token %}
    <div class="form-group">
        <label for="id_username">Usuario</label>
        <input type="text" class="form-control" id="id_username"placeholder="usuario">
      </div>
      <div class="form-group">
          <label for="id_email">Correo electronico</label>
          <input type="text" class="form-control" id="id_email" name="email"placeholder="correo electronico">
      </div>
      <div class="form-group">
          <label for="id_first_name">Nombre</label>
          <input type="text" class="form-control" id="id_first_name" name="first_name"placeholder="nombre">
      </div>
      <div class="form-group">
          <label for="id_last_name">Apellidos</label>
          <input type="text" class="form-control" id="id_last_name" name="last_name"placeholder="apellidos">
      </div>
      <div class="form-group">
        <label for="id_password1">Contraseña</label>
        <input type="password" class="form-control" id="id_password1" name="password1" placeholder="Password">
      </div>
      <div class="form-group">
          <label for="id_password1">Comprobar contraseña</label>
          <input type="password" class="form-control" id="id_password2" name="password2" placeholder="comprobar contraseña">
      </div>
<input type="submit" class="btn btn-primary" value="Registrarse">

</form>
</div>
{% endblock %}
<form>
    
    
  </form>